- .storybook/main.js
- .storybook/preview.js
- package.json
- src/components/QRCode/QRCode.stories.tsx
- src/components/QRCode/index.tsx
- src/pages/fixtures/index.tsx
- src/pages/index.tsx
- yarn.lock
Storybookを導入しました。直接ページに貼り付けなくてもコンポーネントのスタイルを確認できます。
```sh
yarn install
yarn storybook
```
`yarn`を使ってStorybook関係のパッケージをインストールして、`yarn storybook`でStorybookのサーバーを立ち上げます。
ターミナルで定義されたlocalhostにアクセスして、以下のような画面を確認できたらOKです。
レビューについてはこの[ページ](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)を確認してください！
内容を読んでわからないことがあったら #network-questions で質問してください。理解できたら、Scrapboxにまとめページを作成して、 #network で共有してください！
> Storybookの導入

- .github/labels.toml
- .github/workflows/config-gh-labels.yml
GitHubリポジトリのラベルを`.github/labels.toml`で管理するワークフローを追加しました
> GitHubラベルの追加

- package.json
- src/components/QRCodeReader/QRCodeReader.stories.tsx
- src/components/QRCodeReader/index.tsx
- src/pages/fixtures/lending.tsx
- yarn.lock
close #16 
カメラを起動してQRコードを読み取り貸し出し物品のIDを取得し、登録フォームを埋める形で実装
> 「物品を使う」ページを作成した

- package.json
- src/components/FixturesList/FixturesList.stories.tsx
- src/lib/QRCode.ts
- src/pages/items/[fixtures_id].tsx
- src/pages/lending/index.tsx
- src/pages/register/index.tsx
- src/types.ts
- yarn.lock
close #51 
ついでに物品登録ページの更新もしたので #38 も閉じる
> バックエンドAPIをたたくように修正した

- src/components/Item/Item.stories.tsx
- src/components/Item/index.tsx
- src/pages/items/[fixtures_id].tsx
- src/pages/lending/index.tsx
- src/pages/register/index.tsx
> Itemコンポーネントを実装

- src/components/Header/index.tsx
- src/pages/spot/register.tsx
- src/types.ts
> 地点情報の登録ページを作成

- src/pages/lending/index.tsx
> 持っていく場所を登録されたものから選ぶようにした

- src/components/Button/index.tsx
- src/components/Header/index.tsx
- src/components/Select/index.tsx
- src/components/TextArea/index.tsx
- src/components/TextInput/index.tsx
- src/pages/index.tsx
- src/pages/lending/index.tsx
- src/pages/printing/index.tsx
- src/pages/register/index.tsx
- src/pages/spot/register.tsx
- src/types.ts
> デザインをシュッとする

- src/components/FixturesList/index.tsx
> FixturesListコンポーネントに詳細表示機能を追加

- src/components/Header/index.tsx
- src/pages/lending/list.tsx
> 貸し出し中の物品の一覧を閲覧するページを作成

- src/components/LendingList/LendingList.stories.tsx
- src/components/LendingList/index.tsx
- src/pages/lending/index.tsx
- src/pages/lending/list.tsx
- src/types.ts
> 貸し出し中一覧を表示するページの作成

- src/components/Select/index.tsx
- src/components/TextArea/TextArea.stories.tsx
- src/components/TextArea/index.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/index.tsx
- src/lib/fetcher.js
- src/pages/items/[fixtures_id].tsx
- src/pages/lending/index.tsx
- src/pages/register/index.tsx
- src/pages/spot/register.tsx
> 入力が必須かどうかのマークをつけるようにした

- src/components/QRCode/index.tsx
- src/pages/items/[fixtures_id].tsx
- src/pages/printing/index.tsx
close #88 
ついでにQRコードの余白周りをいじった
> 物品ページに貸し出し情報を表示するようにした

- src/components/Header/index.tsx
- src/pages/items/search.tsx
- src/types.ts
> 物品検索ぺーじを追加

- src/components/Header/index.tsx
- src/pages/lending/list.tsx
> 無限APIたたきを修正

- src/components/Header/index.tsx
- src/components/SpotList/SpotList.stories.tsx
- src/components/SpotList/index.tsx
- src/pages/spot/list.tsx
> 場所一覧ページの実装

- src/pages/index.tsx
> トップページにQRコード読み取りボタンを配置し、ページに飛ぶようにした

- src/components/QRCodeReader/QRCodeReader.stories.tsx
- src/components/QRCodeReader/index.tsx
- src/pages/index.tsx
- src/pages/items/register.tsx
- src/pages/lending/index.tsx
> QRコードの値が期待するURLかをチェックする機能を追加

- src/components/FixturesList/index.tsx
- src/components/SpotList/index.tsx
- src/lib/QRCode.ts
- src/pages/items/[qr_id].tsx
- src/pages/items/info_edit.tsx
- src/pages/items/register.tsx
- src/pages/lending/index.tsx
- src/pages/lending/list.tsx
- src/pages/spot/info_edit.tsx
- src/pages/spot/list.tsx
- src/pages/spot/register.tsx
- src/types.ts
> 軽くリファクタリング

- src/types.ts
https://github.com/sohosai/qr-backend/pull/119 に追従
close #117
> エリアのアップデート

- src/components/SpotList/SpotList.stories.tsx
- src/components/SpotList/index.tsx
- src/pages/spot/info_edit.tsx
- src/pages/spot/register.tsx
- src/types.ts
> spotを表示するときに備考を表示する

- src/components/SystemButton/index.tsx
- src/pages/printing/index.tsx
> fix download error handling
